server: Make client context available in de-registration callback
eclipse-wakaama/wakaama pull request #666
Opened 2022-06-15 11:45 UTC by mlasch

Remove the client from server context only after calling the monitoring callback when handling a de-registration. A as result, the client information is still available in the server context during the callback.

Signed-off-by: Marc Lasch <marc.lasch@husqvarnagroup.com>

2022-07-06 07:29 UTC, rettichschnidi requested changes
How did this get tested? Any chance for an automated test?

2022-07-06 07:29 UTC, rettichschnidi commented on core/registration.c
> -
Please leave out unrelated, cosmetic changes.

2022-07-06 07:29 UTC, rettichschnidi commented on core/registration.c
> +        if (!LWM2M_URI_IS_SET_OBJECT(uriP))
Please always add curly braces.

2023-03-03 15:14 UTC, rettichschnidi requested changes
Why not just changing the interface of the monitor callback to include a reference to client instead of just the clientID? This way, the client reference *can* be removed from the list before calling the monitor callback.

2023-03-03 15:14 UTC, rettichschnidi commented on examples/server/lwm2mserver.c
> +    prv_dump_client(clientP);
Is it intended to do this even when returning COAP_202_DELETED?

2025-01-22 14:09 UTC, LukasWoodtli commented
LGTM

2025-01-22 14:10 UTC, LukasWoodtli approved these changes

2025-01-22 14:13 UTC, mlasch commented on examples/server/lwm2mserver.c
> +    prv_dump_client(clientP);
yes

2025-03-03 09:49 UTC, mlasch commented
> Why not just changing the interface of the monitor callback to include a reference to client instead of just the clientID? This way, the client reference _can_ (not sure if sensible) be removed from the list before calling the monitor callback.

This would be an alternative, but it would require quite significant changes in the whole code base. I would prefer to keep it as is for now. Can you open a ticket so this can be discussed in a broader sense?

2025-03-03 09:56 UTC, merged