doc: Build doxygen documentation
eclipse-wakaama/wakaama pull request #816
Opened 2024-10-24 06:22 UTC by LukasWoodtli

The Doxygen documentation is generated and uploaded with GitHub actions.

Currently the code is not yet thoroughly documented.

2024-10-24 07:49 UTC, rettichschnidi requested changes

2024-10-24 07:49 UTC, rettichschnidi commented on doc/doxygen/Doxyfile
> +CASE_SENSE_NAMES       = NO
CI runs on Linux - should this be Yes or at least the default?

2024-10-24 07:49 UTC, rettichschnidi commented on doc/doxygen/Doxyfile
> +HTML_FORMULA_FORMAT    = png
```suggestion
HTML_FORMULA_FORMAT    = svg
```

2024-10-24 07:49 UTC, rettichschnidi commented on doc/doxygen/Doxyfile
> +PLANTUML_JAR_PATH      =
Would install platnuml via apt and enable support for it:
```suggestion
PLANTUML_JAR_PATH      = /usr/share/plantuml/plantuml.jar
```

2024-10-24 07:49 UTC, rettichschnidi commented on tools/ci/run_ci.sh
> +    GIT_REVISION=$(git rev-parse @) WORKING_DIR=$(pwd) DOXYGEN_OUT_DIR=build-wakaama/doxygen_out \
Would use either a dash, such as in build*-*wakaama:
```suggestion
    GIT_REVISION=$(git rev-parse @) WORKING_DIR=$(pwd) DOXYGEN_OUT_DIR=build-wakaama/doxygen-out \
```

Or just leave out the `_out` part:
```suggestion
    GIT_REVISION=$(git rev-parse @) WORKING_DIR=$(pwd) DOXYGEN_OUT_DIR=build-wakaama/doxygen \
```

2024-10-24 07:49 UTC, rettichschnidi commented on .github/workflows/documentation.yaml
> +        path: build-wakaama/doxygen_out
```suggestion
        path: build-wakaama/doxygen-out
```

or
```suggestion
        path: build-wakaama/doxygen
```

(see other comment)

2024-10-29 11:48 UTC, rettichschnidi approved these changes
LGTM, just two nits.

2024-10-29 11:48 UTC, rettichschnidi commented on .github/workflows/documentation.yaml
> +        submodules: true
I just checked out without submodules and build the documentation. It does not seem like submodules are actually needed.

2024-10-29 11:48 UTC, rettichschnidi commented on doc/doxygen/Doxyfile
Looking really good.

One tiny nit, likely not worth investing time into: The tab "Related Pages" shows the exact same content as "Main Page".

![image](https://github.com/user-attachments/assets/9063c83a-d4a6-49d9-8e6a-61d1a9937c02)

2024-10-29 13:19 UTC, LukasWoodtli commented on doc/doxygen/Doxyfile
Now the "Related Pages" tab shows additional files:
![image](https://github.com/user-attachments/assets/c421ef41-b463-4910-be3f-236e28b25aae)

2024-10-29 13:26 UTC, rettichschnidi commented on doc/doxygen/Doxyfile
All links are still on the same page (README.md), but this clearly an improvement.

2024-10-29 13:50 UTC, merged