Lw/client examples as individual projects
eclipse-wakaama/wakaama pull request #818
Opened 2024-10-31 08:47 UTC by LukasWoodtli

2024-11-24 19:29 UTC, rettichschnidi requested changes
Just had a (very) brief look and noticed the following CMake warnings that did not show up before:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    WAKAAMA_ENABLE_EXAMPLES
```

Will have a close(r) look once this is resolved.

2024-11-24 20:41 UTC, LukasWoodtli commented
> Just had a (very) brief look and noticed the following CMake warnings that did not show up before:
> 
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     WAKAAMA_ENABLE_EXAMPLES
> ```
> 
> Will have a close(r) look once this is resolved.

Thank you for the hint. Removing that is part of the next PR (wip) with some clean-ups.
I decided to split a bigger change (#808) into smaller ones for better reviewing.

2024-11-27 15:18 UTC, rettichschnidi requested changes
Please rebase on latest main before merging. The CI might fail then:

```
$ git rebase upstream/main 
 .github/workflows/build.yaml                 |   8 ++++++--
 .github/workflows/build_and_test.yaml        |   9 ++++++---
 .github/workflows/clang-static-analyzer.yaml |   8 ++++++--
 .github/workflows/codeql-analysis.yml        |  10 +++++++---
 .github/workflows/compliance.yaml            |   8 ++++++--
 .github/workflows/coverage.yaml              |   8 ++++++--
 .github/workflows/documentation.yaml         |   8 ++++++--
 .github/workflows/macos.yaml                 |   6 +++++-
 .github/workflows/multiarch.yaml             |   8 ++++++--
 .github/workflows/scorecard.yml              |  61 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 .github/workflows/sonarcloud-scan.yaml       |   8 ++++++--
 CONTRIBUTING.md                              |   2 +-
 NOTICE.md                                    |   2 +-
 README.md                                    |  22 ++++++++++++---------
 doc/wakaama_features.rst                     | 213 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 examples/shared/platform.c                   |   2 +-
 tests/data_senml_json_tests.c                |   2 +-
 tests/integration/requirements.txt           |  15 ++++++++++++--
 tools/ci/run_ci.sh                           |   5 +++--
 tools/requirements-compliance.txt            |  31 ++++++++++++++++++++++++++---
 20 files changed, 395 insertions(+), 41 deletions(-)
 create mode 100644 .github/workflows/scorecard.yml
 create mode 100644 doc/wakaama_features.rst
Successfully rebased and updated refs/heads/lw/client_examples_as_individual_projects.
$ tools/ci/run_ci.sh --all
no modified files to format
diff --git a/examples/client/common/object_firmware.c b/examples/client/common/object_firmware.c
index aa39a6c..8631cd9 100644
--- a/examples/client/common/object_firmware.c
+++ b/examples/client/common/object_firmware.c
@@ -59,7 +59,7 @@
 #define RES_M_UPDATE_METHOD 9
 
 #define LWM2M_FIRMWARE_PROTOCOL_NUM 4
-#define LWM2M_FIRMWARE_PROTOCOL_NULL ((uint8_t) - 1)
+#define LWM2M_FIRMWARE_PROTOCOL_NULL ((uint8_t)-1)
 
 typedef struct {
     uint8_t state;
```

2024-11-28 10:11 UTC, rettichschnidi approved these changes

2024-12-03 14:21 UTC, merged