fix a memory leak bug about a registion update request without a reply
eclipse-wakaama/wakaama pull request #823
Opened 2024-11-13 16:03 UTC by xiaoshan1234

fix a memory leak bug about a registion update request without a reply
refer to https://github.com/eclipse-wakaama/wakaama/issues/811

2024-11-24 12:07 UTC, rettichschnidi commented
@xiaoshan1234 Thanks for contribution. However, before we can take it, we need you to sign the Eclipse Contributor Agreement. You can find details here: https://api.eclipse.org/git/eca/status/gh/eclipse-wakaama/wakaama/823

2024-11-24 12:08 UTC, rettichschnidi requested changes
@xiaoshan1234 Thanks for contribution. However, before we can take it, we need you to sign the Eclipse Contributor Agreement. You can find details here: https://api.eclipse.org/git/eca/status/gh/eclipse-wakaama/wakaama/823

Once you have done this, I'll conduct a review of your code changes.

2025-04-23 10:11 UTC, mlasch commented on core/registration.c
> +    if (packet != NULL && packet->code == COAP_231_CONTINUE)
Hi, why do you invert the check here?

2025-04-23 12:45 UTC, xiaoshan1234 commented on core/registration.c
> +    if (packet != NULL && packet->code == COAP_231_CONTINUE)
when a continue packet arrived，do nothing，when a Null or non-continue packet arrived，free the update resources

2025-04-25 19:37 UTC, mlasch commented on core/registration.c
> +    if (packet != NULL && packet->code == COAP_231_CONTINUE)
ok I understand. But I would rather keep the `if` statement as is, then there is no need for the else branch as well as the empty `{ ; // pass  }` block.

Also, can you run `git clang-format HEAD~1` on your commit to format the code according to the rules enforced by the CI pipeline?

2025-04-25 19:38 UTC, mlasch commented
As @rettichschnidi mentioned above, for your PR to get merged, Eclipse requires contributors to sign the Eclipse Contributor Agreement.

2025-04-26 07:08 UTC, xiaoshan1234 commented on core/registration.c
> +    if (packet != NULL && packet->code == COAP_231_CONTINUE)
In the original version, the registion update resource will not be freed when a Null packet arrived. That is the problem.

2025-04-26 07:12 UTC, xiaoshan1234 commented
> As @rettichschnidi mentioned above, for your PR to get merged, Eclipse requires contributors to sign the [Eclipse Contributor Agreement](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git).

3q for the reminder, I have signed ECA just now with the same email

2025-04-26 13:57 UTC, closed without merging