Clean up CMake configs
eclipse-wakaama/wakaama pull request #838
Opened 2024-12-04 16:04 UTC by LukasWoodtli

2024-12-05 07:59 UTC, rettichschnidi requested changes

2024-12-05 07:59 UTC, rettichschnidi commented on wakaama.cmake
> +option(WAKAAMA_MODE_BOOTSTRAP_SERVER "Enable LWM2M Bootstrap Server interfaces" ON)
```suggestion
option(WAKAAMA_MODE_BOOTSTRAP_SERVER "Enable LwM2M Bootstrap Server interfaces" ON)
```

2024-12-05 07:59 UTC, rettichschnidi commented on wakaama.cmake
> +option(WAKAAMA_MODE_CLIENT "Enable LWM2M Client interfaces" ON)
```suggestion
option(WAKAAMA_MODE_CLIENT "Enable LwM2M Client interfaces" ON)
```

2024-12-17 12:39 UTC, rettichschnidi approved these changes
LGTM

2024-12-17 13:55 UTC, LukasWoodtli commented on .github/workflows/build_and_test.yaml
> +        example: ["bootstrap_server", "client/udp", "client/tinydtls", "client/raw_block1", "lightclient", "server"]
Good to know! Thanks!

2024-12-17 15:32 UTC, merged